language: java 
deploy:
  provider: heroku
  api_key:
    secure: xiQ/mH2LS03WDZQDxhBcgBsduHTpXL9ClOtQrZ6XFEamliTnhKHJ25einfMFLi/udKZgybrQqi70hixkZbHSCXB2L+D+m+nIMwYo8t3aYJNSDTFvhnK0R/OQHuFQSYnKkIP2xp6o1QJOByltzLEYEr/QYgTKccINEL8W9EppSza6MmlaFCM5R2kzCNk+HN27Bt5JMI2gBjqQYI5SVzLRifUcJ5z0y/3CrSN4ixTyEitRNqdMz6Kxft086r9PvZc4USHOiLqjxKMxD8/kKQNWB+D35em4Nyat6LlAn17tE9wyvMBi8yemgT7jOkYvyvnlk81MQoBdArbqICkN7u7LFGtBVsVCPlLq4TybDHwM+cn2bASq6HgztVwkvz+WKVu8p2b9gEtKU/LKfXuBoJwR8FcXqr1nvOzlSpXhA2cVY6CDVlAEbhJtkWTbJ+I1jpLHrqqz3JmUqc11F6MPH56oFVZopZcBlHdZd3+BN+FTUbikHJ+1zM22IoVlh9SBkqG4wa+r+ZyjAc0GsWvgs+1jawyKhToAlCtTsgSiiIMyBO6lTEMPkw0d1ksEAXPi/wUGTiS8stW046d6sK/C7mipCMeq81/Dk1n4P8zw6EXlTbNCW66yElljgss299eazbxFmEBltzxwRO8rDJbTsiR+RPl49QW8DqXgKExaGILwbHY=
  app: unitservice 
  on:
    repo: pussinboots/unitservice
